version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    cooldown:
      default-days: 3
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: typescript
        versions: ~7.0.0
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      npm:
        patterns:
          - '*'
