packages:
  - ./cdk
  - ./app

overrides:
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
  # eslint: ">=10.0.0"
  # '@eslint/js': ">=10.0.0"
  eslint: "^9"
  '@eslint/js': "^9"
  '@stylistic/eslint-plugin': '>=5.0.0'
