name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

env:
  OIDC_IAM_ROLE_ARN: ${{ secrets.OIDC_IAM_ROLE_ARN }}
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

# 同時実行すると CREATE_IN_PROGRESS や UPDATE_IN_PROGRESS 状態で cdk deploy を行う可能性があるため抑止する
concurrency:
  group: ${{ github.workflow }}-cloudformation
  cancel-in-progress: false

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [24.x]

    runs-on: ubuntu-24.04-arm
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ env.OIDC_IAM_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - uses: actions/checkout@v5

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]
          - args: [--global, aws-cdk, esbuild]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: pnpm

    - name: deploy
      working-directory: cdk
      run: cdk deploy -c clientId=${{ secrets.CLIENT_ID }} -c clientSecret=${{ secrets.CLIENT_SECRET }}

    - name: Retirives CloudFront Distribution Domain Name
      id: distribution-url
      run: |
        CF_ID="$(aws cloudformation describe-stack-resources --stack-name github-sbom-viewer --query 'StackResources[?ResourceType==`AWS::CloudFront::Distribution`].[PhysicalResourceId][]' --output text)"
        CF_DOMAIN="$(aws cloudfront get-distribution --id "$CF_ID" --query 'Distribution.DomainName' --output text)"
        echo "cloudfront-domain-name=$CF_DOMAIN" >> "$GITHUB_OUTPUT"

    - name: deploy(Update Lambda Config)
      working-directory: cdk
      env:
        CF_DOMAIN: ${{ steps.distribution-url.outputs.cloudfront-domain-name }}
      run: cdk deploy -c clientId=${{ secrets.CLIENT_ID }} -c clientSecret=${{ secrets.CLIENT_SECRET }} -c domain="$CF_DOMAIN"
